version: "3.7"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clients
      POSTGRES_USER: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: 'postgres -c max_connections=1000 -c shared_buffers=128MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "270MB"

  api01: &api
    image: podinho/rinhav2:latest
    hostname: api01
    ports:
      - "3001:3000"
    restart: always
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "130MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "3002:3000"

  nginx:
    image: nginx:stable-perl
    hostname: nginx
    ports:
      - "9999:9999"
    restart: always
    depends_on:
      - api01
      - api02
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

networks:
  default:
    driver: bridge
    name: rinhav22222
