version: "3.7"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:    
      POSTGRES_PASSWORD: postgres
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"
    networks:
      - rinhav22222

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    networks:
      - rinhav22222

networks:
  rinhav22222:
    driver: bridge